### PR TITLE
[UI] New Act Log button + mood log ui adjustment

### PR DESCRIPTION
**Pull request by franzsamilo**

### CODE REVIEW

**Comment by cezro** [comment]
this code is absolute garbage👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺👺, approved

**Review by cezro — APPROVED** [review]
garbage👺**👺👺👺👺👺👺👺**

**Comment by franzsamilo** [comment]
awww

**Comment by franzsamilo** [comment]
merged

**Pull request merged**
